### ISSUE TITLE
PathCLIP model weight release？

### ISSUE THREAD

**Issue by Hanminghao** [superjamessyx/Generative-Foundation-AI-Assistant-for-Pathology#3]
Very good work, may I ask when the fully trained PathCLIP weight can be announced?

**Comment by superjamessyx** [comment]
Hello, sorry for the late response. We have uploaded our model to Hugging Face. You can download it from https://huggingface.co/jamessyx/pathclip.

**Comment by superjamessyx** [comment]
> Very good work, may I ask when the fully trained PathCLIP weight can be announced?

Hello, sorry for the late response. We have uploaded our model to Hugging Face. You can download it from https://huggingface.co/jamessyx/pathclip.

**Comment by Hanminghao** [comment]
Thank you for your reply.
