### ISSUE TITLE
Convnext Implementation

### ISSUE THREAD

**Issue by ZeyuGaoAi** [superjamessyx/Generative-Foundation-AI-Assistant-for-Pathology#5]
Dear Authors, 

I tried to use the ConvNext-tiny that you provided in huggingface.
Could you please provide which implementation of ConvNext you used? From the readme "from model_factory.modeling_convnext import CT_SINGLE", I cannot locate the right implementation or package for the ConvNext-tiny.

Many thanks!

**Comment by superjamessyx** [comment]
> Dear Authors,
> 
> I tried to use the ConvNext-tiny that you provided in huggingface. Could you please provide which implementation of ConvNext you used? From the readme "from model_factory.modeling_convnext import CT_SINGLE", I cannot locate the right implementation or package for the ConvNext-tiny.
> 
> Many thanks!

Sorry for missing the important model definition of "CT_SINGLE", we have updated the details and the instructions for this model at https://github.com/superjamessyx/Generative-Foundation-AI-Assistant-for-Pathology/tree/main/pathology_classifier.

**Comment by ZeyuGaoAi** [comment]
Thanks a lot!
